color0 #424753
color1 #ffb4ab
color2 #aec6ff
color3 #b1c6f9
color4 #f2afff
color5 #aec6ff
color6 #b1c6f9
color7 #e1e2ec
color8 #8c909f
color9 #ffb4ab
color10 #aec6ff
color11 #b1c6f9
color12 #f2afff
color13 #aec6ff
color14 #b1c6f9
color15 #e1e2ec

cursor                #e1e2ec
cursor_text_color     #11131a
background            #11131a
foreground            #e1e2ec
selection_foreground  #c2c6d6
selection_background  #424753
active_border_color   #aec6ff
inactive_border_color #424753
url_color             #aec6ff

active_tab_foreground   #002e6a
active_tab_background   #aec6ff
inactive_tab_foreground #c2c6d6
inactive_tab_background #424753
cursor_trail_color      #c2c6d6
